name: Unit Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  unitTests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Execute Unit Test Command
        run: bash ./gradlew test